#spring:
#  rsocket:
#    server:
#      port: 7000
#      transport: tcp
server:
  port: 8080

---

spring:
  profiles:
    active: local
  r2dbc:
    url: postgresql://localhost/postgres
    username: postgres
    password: secret
  jpa:
    show-sql: true
    generate-ddl: true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc=DEBUG: debug

---

spring:
  profiles: prod

  r2dbc:
    url: postgresql://pay_postgres/postgres
    username: postgres
    password: secret
    name: postgres

