spring:
  rsocket:
    server:
      port: 7000
      transport: tcp

---

spring:
  profiles:
    active: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pay_manager

---

spring:
  profiles: prod
  data:
    mongodb:
      host: pay-mongodb
      port: 27017
      database: pay_manager