#spring:
#  rsocket:
#    server:
#      port: 7000
#      transport: tcp
server:
  port: 8080

---

spring:
  profiles:
    active: local
  r2dbc:
    url: postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  reactor:
    debug-agent:
      enabled: true


logging:
  level:
    org:
      springframework:
        data:
          r2dbc:
            DEBUG: debug
---

spring:
  profiles: prod

  r2dbc:
    url: postgresql://pay_postgres/postgres
    username: postgres
    password: secret
    name: postgres

