
CREATE TABLE PAY_USER (ID INTEGER PRIMARY KEY, NAME VARCHAR(30));

CREATE TABLE PAY_TOKEN (
ID INTEGER PRIMARY KEY,
TOKEN VARCHAR(17),
 USE_YN VARCHAR(7),
 SPRINKLE_ID INTEGER,

  GENERATE_DATE VARCHAR(30),
   COMPLETE_DATE VARCHAR(30),
   )

CREATE TABLE PAY_SPRINKLE (
ID INTEGER PRIMARY KEY,
TOKEN_ID INTEGER,
SPRINKLE_USER INTEGER,
 ROOM_NAME VARCHAR(150),
  SPRINKLE_PRICE INTEGER,
  DIVIDE INTEGER,
  START_DATE VARCHAR(30)
  )

CREATE TABLE PAY_RECEIVE (
ID INTEGER PRIMARY KEY,
RECEIVE_USER INTEGER,
TOKEN_ID INTEGER,
ROOM_NAME VARCHAR(150),
RECEIVE_PRICE INTEGER
)


CREATE TABLE SPRINKLE_RECEIVE_MAP (
ID INTEGER PRIMARY KEY,
SPRINKLE_ID INTEGER,
RECEIVE_ID INTEGER,
TOKEN_ID INTEGER,
PRICE INTEGER,
ROOM_NAME VARCHAR(150)
)