
CREATE TABLE PAY_USER (ID INTEGER PRIMARY KEY, NAME VARCHAR(30));

CREATE TABLE PAY_TOKEN (
    ID INTEGER PRIMARY KEY,
    TOKEN VARCHAR(17),
    USE_YN VARCHAR(7),
--     SPRINKLE_ID INTEGER,
    GENERATE_DATE VARCHAR(33),
    EXPIRE_DATE VARCHAR(33)
);


CREATE TABLE TOKEN_NODE (
    ID INTEGER PRIMARY KEY,
    PARENT_TOKEN VARCHAR(17),
    RECEIVE_ID INTEGER,
    RECEIVE_DATE VARCHAR(33)
)

CREATE TABLE PAY_SPRINKLE (
    ID INTEGER PRIMARY KEY,
    TOKEN_ID INTEGER,
    SPRINKLE_USER INTEGER,
    ROOM_NAME VARCHAR(33),
    SPRINKLE_PRICE INTEGER,
    DIVIDE INTEGER,
    START_DATE VARCHAR(30),
    SOLD_OUT_DATE VARCHAR(33)
)
-- RECEIVE 는 받기 할 때마다 테이블이 생성된다.

CREATE TABLE PAY_RECEIVE (
    ID INTEGER PRIMARY KEY,
    RECEIVE_USER INTEGER,
    TOKEN_ID INTEGER,
    ROOM_NAME VARCHAR(33),
    RECEIVE_PRICE INTEGER,
    SPRINKLE_DATE VARCHAR(33),
    RECEIVE_DATE VARCHAR(33)
)


